version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=Nozer
      - POSTGRES_PASSWORD=p0stgr3sql
      - POSTGRES_DB=shortlinks
    volumes:
      - postgres_data:/bitnami/postgresql/postgres_data

  redis:
    image: bitnami/redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=r3d1sql
    volumes:
      - redis_data:/bitnami/redis/redis_data

volumes:
  postgres_data:
  redis_data: